name: publish image to docker hub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version : [21.x]
          os: [ubuntu-latest]
          arch: [amd64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/dotnetdudes-vite-website:latest
          file: ./Dockerfile
          build-args: |
            NODE_VERSION=${{ matrix.node-version }}
            OS=${{ matrix.os }}
            ARCH=${{ matrix.arch }}
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_API_KEY=${{ secrets.VITE_API_KEY }}
            VITE_AUTH_SERVER_URL=${{ secrets.VITE_AUTH_SERVER_URL }}
            VITE_AUTH_SERVER_CLIENT_ID=${{ secrets.VITE_AUTH_SERVER_CLIENT_ID }}
            VITE_AUTH_SERVER_REALM=${{ secrets.VITE_AUTH_SERVER_REALM }}

      - name: Image digest
        run: echo ${{ steps.docker.outputs.digest }}